import { CustomTheme } from "./types";

export const variableVals = [
  "--background",
  "--foreground",
  "--muted",
  "--muted-foreground",
  "--popover",
  "--popover-foreground",
  "--card",
  "--card-foreground",
  "--border",
  "--input",
  "--primary",
  "--primary-foreground",
  "--secondary",
  "--secondary-foreground",
  "--accent",
  "--accent-foreground",
  "--destructive",
  "--destructive-foreground",
  "--ring",
] as const;

export const availableThemes = ["dark", "light", "system", "custom"] as const;

export const defaultDarkTheme: CustomTheme = {
  name: "default dark",
  themeVariableMap: {
    "--accent": {
      cssVarName: "--accent",
      inherits: ["--border", "--input", "--ring"],
      label: "accent",
      value: { h: 217.2, l: 17.5, s: 32.6 },
      varNotFound: false,
    },
    "--accent-foreground": {
      cssVarName: "--accent-foreground",
      inheritedFrom: "--primary",
      label: "accent foreground",
      value: { h: 210, l: 98, s: 40 },
      varNotFound: false,
    },
    "--background": {
      cssVarName: "--background",
      inherits: ["--popover", "--card"],
      label: "background",
      value: { h: 222.2, l: 4.9, s: 84 },
      varNotFound: false,
    },
    "--border": {
      cssVarName: "--border",
      inheritedFrom: "--accent",
      label: "border",
      value: { h: 217.2, l: 17.5, s: 32.6 },
      varNotFound: false,
    },
    "--card": {
      cssVarName: "--card",
      inheritedFrom: "--background",
      label: "card",
      value: { h: 222.2, l: 4.9, s: 84 },
      varNotFound: false,
    },
    "--card-foreground": {
      cssVarName: "--card-foreground",
      label: "card foreground",
      value: { h: 210, l: 98, s: 40 },
      varNotFound: true,
    },
    "--destructive": {
      cssVarName: "--destructive",
      label: "destructive",
      value: { h: 0, l: 30.6, s: 62.8 },
      varNotFound: false,
    },
    "--destructive-foreground": {
      cssVarName: "--destructive-foreground",
      inheritedFrom: "--primary",
      label: "destructive foreground",
      value: { h: 0, l: 97.3, s: 85.7 },
      varNotFound: false,
    },
    "--foreground": {
      cssVarName: "--foreground",
      label: "foreground",
      value: { h: 210, l: 98, s: 40 },
      varNotFound: false,
    },
    "--input": {
      cssVarName: "--input",
      inheritedFrom: "--accent",
      label: "input",
      value: { h: 217.2, l: 17.5, s: 32.6 },
      varNotFound: false,
    },
    "--muted": {
      cssVarName: "--muted",
      label: "muted",
      value: { h: 217.2, l: 17.5, s: 32.6 },
      varNotFound: false,
    },
    "--muted-foreground": {
      cssVarName: "--muted-foreground",
      label: "muted foreground",
      value: { h: 215, l: 65.1, s: 20.2 },
      varNotFound: false,
    },
    "--popover": {
      cssVarName: "--popover",
      inheritedFrom: "--background",
      label: "popover",
      value: { h: 222.2, l: 4.9, s: 84 },
      varNotFound: false,
    },
    "--popover-foreground": {
      cssVarName: "--popover-foreground",
      label: "popover foreground",
      value: { h: 210, l: 98, s: 40 },
      varNotFound: false,
    },
    "--primary": {
      cssVarName: "--primary",
      inherits: [
        "--secondary-foreground",
        "--accent-foreground",
        "--destructive-foreground",
      ],
      label: "primary",
      value: { h: 210, l: 98, s: 40 },
      varNotFound: false,
    },
    "--primary-foreground": {
      cssVarName: "--primary-foreground",
      label: "primary foreground",
      value: { h: 222.2, l: 11.2, s: 47.4 },
      varNotFound: false,
    },
    "--ring": {
      cssVarName: "--ring",
      inheritedFrom: "--accent",
      label: "ring",
      value: { h: 217.2, l: 17.5, s: 32.6 },
      varNotFound: false,
    },
    "--secondary": {
      cssVarName: "--secondary",
      label: "secondary",
      value: { h: 217.2, l: 17.5, s: 32.6 },
      varNotFound: false,
    },
    "--secondary-foreground": {
      cssVarName: "--secondary-foreground",
      inheritedFrom: "--primary",
      label: "secondary foreground",
      value: { h: 210, l: 98, s: 40 },
      varNotFound: false,
    },
  },
};

export const defaultLightTheme: CustomTheme = {
  name: "default light",
  themeVariableMap: {
    "--accent": {
      cssVarName: "--accent",
      inherits: ["--border", "--input", "--ring"],
      label: "accent",
      value: { h: 210, l: 96.1, s: 40 },
      varNotFound: false,
    },
    "--accent-foreground": {
      cssVarName: "--accent-foreground",
      inheritedFrom: "--primary",
      label: "accent foreground",
      value: { h: 222.2, l: 11.2, s: 47.4 },
      varNotFound: false,
    },
    "--background": {
      cssVarName: "--background",
      inherits: ["--popover", "--card"],
      label: "background",
      value: { h: 0, l: 100, s: 0 },
      varNotFound: false,
    },
    "--border": {
      cssVarName: "--border",
      inheritedFrom: "--accent",
      label: "border",
      value: { h: 214.3, l: 91.4, s: 31.8 },
      varNotFound: false,
    },
    "--card": {
      cssVarName: "--card",
      inheritedFrom: "--background",
      label: "card",
      value: { h: 0, l: 100, s: 0 },
      varNotFound: false,
    },
    "--card-foreground": {
      cssVarName: "--card-foreground",
      label: "card foreground",
      value: { h: 222.2, l: 4.9, s: 84 },
      varNotFound: true,
    },
    "--destructive": {
      cssVarName: "--destructive",
      label: "destructive",
      value: { h: 0, l: 60.2, s: 84.2 },
      varNotFound: false,
    },
    "--destructive-foreground": {
      cssVarName: "--destructive-foreground",
      inheritedFrom: "--primary",
      label: "destructive foreground",
      value: { h: 210, l: 98, s: 40 },
      varNotFound: false,
    },
    "--foreground": {
      cssVarName: "--foreground",
      label: "foreground",
      value: { h: 222.2, l: 4.9, s: 84 },
      varNotFound: false,
    },
    "--input": {
      cssVarName: "--input",
      inheritedFrom: "--accent",
      label: "input",
      value: { h: 214.3, l: 91.4, s: 31.8 },
      varNotFound: false,
    },
    "--muted": {
      cssVarName: "--muted",
      label: "muted",
      value: { h: 210, l: 96.1, s: 40 },
      varNotFound: false,
    },
    "--muted-foreground": {
      cssVarName: "--muted-foreground",
      label: "muted foreground",
      value: { h: 215.4, l: 46.9, s: 16.3 },
      varNotFound: false,
    },
    "--popover": {
      cssVarName: "--popover",
      inheritedFrom: "--background",
      label: "popover",
      value: { h: 0, l: 100, s: 0 },
      varNotFound: false,
    },
    "--popover-foreground": {
      cssVarName: "--popover-foreground",
      label: "popover foreground",
      value: { h: 222.2, l: 4.9, s: 84 },
      varNotFound: false,
    },
    "--primary": {
      cssVarName: "--primary",
      inherits: [
        "--secondary-foreground",
        "--accent-foreground",
        "--destructive-foreground",
      ],
      label: "primary",
      value: { h: 222.2, l: 11.2, s: 47.4 },
      varNotFound: false,
    },
    "--primary-foreground": {
      cssVarName: "--primary-foreground",
      label: "primary foreground",
      value: { h: 210, l: 98, s: 40 },
      varNotFound: false,
    },
    "--ring": {
      cssVarName: "--ring",
      inheritedFrom: "--accent",
      label: "ring",
      value: { h: 215, l: 65.1, s: 20.2 },
      varNotFound: false,
    },
    "--secondary": {
      cssVarName: "--secondary",
      label: "secondary",
      value: { h: 210, l: 96.1, s: 40 },
      varNotFound: false,
    },
    "--secondary-foreground": {
      cssVarName: "--secondary-foreground",
      inheritedFrom: "--primary",
      label: "secondary foreground",
      value: { h: 222.2, l: 11.2, s: 47.4 },
      varNotFound: false,
    },
  },
};
